/*
* generated by Xtext
*/
package co.edu.uniandes.enar.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import co.edu.uniandes.enar.services.PictureGrammarAccess;

public class PictureParser extends AbstractContentAssistParser {
	
	@Inject
	private PictureGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected co.edu.uniandes.enar.ui.contentassist.antlr.internal.InternalPictureParser createParser() {
		co.edu.uniandes.enar.ui.contentassist.antlr.internal.InternalPictureParser result = new co.edu.uniandes.enar.ui.contentassist.antlr.internal.InternalPictureParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getMetaConceptReferenceAccess().getAlternatives(), "rule__MetaConceptReference__Alternatives");
					put(grammarAccess.getStyleElementAccess().getAlternatives(), "rule__StyleElement__Alternatives");
					put(grammarAccess.getLineDecorationAccess().getAlternatives(), "rule__LineDecoration__Alternatives");
					put(grammarAccess.getDefaultLineDecorationAccess().getAlternatives(), "rule__DefaultLineDecoration__Alternatives");
					put(grammarAccess.getLayoutAccess().getAlternatives(), "rule__Layout__Alternatives");
					put(grammarAccess.getDefaultLayoutAccess().getAlternatives(), "rule__DefaultLayout__Alternatives");
					put(grammarAccess.getFigureStyleAccess().getAlternatives(), "rule__FigureStyle__Alternatives");
					put(grammarAccess.getLabelPositionAccess().getAlternatives(), "rule__LabelPosition__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getGraphicalElementAccess().getAlternatives(), "rule__GraphicalElement__Alternatives");
					put(grammarAccess.getElementDefAccess().getAlternatives(), "rule__ElementDef__Alternatives");
					put(grammarAccess.getNodeDefAccess().getAlternatives(), "rule__NodeDef__Alternatives");
					put(grammarAccess.getAttLinkDefAccess().getAlternatives(), "rule__AttLinkDef__Alternatives");
					put(grammarAccess.getElementAltAccess().getAlternatives(), "rule__ElementAlt__Alternatives");
					put(grammarAccess.getNodeAltAccess().getAlternatives(), "rule__NodeAlt__Alternatives");
					put(grammarAccess.getAttLinkAltAccess().getAlternatives(), "rule__AttLinkAlt__Alternatives");
					put(grammarAccess.getFigureAccess().getAlternatives(), "rule__Figure__Alternatives");
					put(grammarAccess.getRuleAccess().getAlternatives(), "rule__Rule__Alternatives");
					put(grammarAccess.getCaseTypeAccess().getAlternatives_4(), "rule__CaseType__Alternatives_4");
					put(grammarAccess.getCaseReferenceAccess().getAlternatives_4(), "rule__CaseReference__Alternatives_4");
					put(grammarAccess.getInteractionElementAccess().getAlternatives(), "rule__InteractionElement__Alternatives");
					put(grammarAccess.getWizardAccess().getAlternatives(), "rule__Wizard__Alternatives");
					put(grammarAccess.getViewAccess().getAlternatives(), "rule__View__Alternatives");
					put(grammarAccess.getViewTypeAccess().getAlternatives(), "rule__ViewType__Alternatives");
					put(grammarAccess.getViewStyleAccess().getAlternatives(), "rule__ViewStyle__Alternatives");
					put(grammarAccess.getEventTypeAccess().getAlternatives(), "rule__EventType__Alternatives");
					put(grammarAccess.getMouseEventAccess().getAlternatives(), "rule__MouseEvent__Alternatives");
					put(grammarAccess.getKeyEventAccess().getAlternatives(), "rule__KeyEvent__Alternatives");
					put(grammarAccess.getElementEventAccess().getAlternatives(), "rule__ElementEvent__Alternatives");
					put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
					put(grammarAccess.getLineTypeAccess().getAlternatives(), "rule__LineType__Alternatives");
					put(grammarAccess.getWizardTypeAccess().getAlternatives(), "rule__WizardType__Alternatives");
					put(grammarAccess.getComponentTypeAccess().getAlternatives(), "rule__ComponentType__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getGraphicalRepresentationAccess().getGroup(), "rule__GraphicalRepresentation__Group__0");
					put(grammarAccess.getGraphicalRepresentationAccess().getGroup_4(), "rule__GraphicalRepresentation__Group_4__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getClassReferenceAccess().getGroup(), "rule__ClassReference__Group__0");
					put(grammarAccess.getAttReferenceAccess().getGroup(), "rule__AttReference__Group__0");
					put(grammarAccess.getROOTAccess().getGroup(), "rule__ROOT__Group__0");
					put(grammarAccess.getToolDefinitionAccess().getGroup(), "rule__ToolDefinition__Group__0");
					put(grammarAccess.getToolGroupAccess().getGroup(), "rule__ToolGroup__Group__0");
					put(grammarAccess.getCreationButtonAccess().getGroup(), "rule__CreationButton__Group__0");
					put(grammarAccess.getStyleDefinitionAccess().getGroup(), "rule__StyleDefinition__Group__0");
					put(grammarAccess.getLineStyleAccess().getGroup(), "rule__LineStyle__Group__0");
					put(grammarAccess.getDefaultLineDecorationAccess().getGroup_3(), "rule__DefaultLineDecoration__Group_3__0");
					put(grammarAccess.getDefaultLineDecorationAccess().getGroup_5(), "rule__DefaultLineDecoration__Group_5__0");
					put(grammarAccess.getDefaultLineDecorationAccess().getGroup_6(), "rule__DefaultLineDecoration__Group_6__0");
					put(grammarAccess.getDefaultLineDecorationAccess().getGroup_7(), "rule__DefaultLineDecoration__Group_7__0");
					put(grammarAccess.getCustomLineDecorationAccess().getGroup(), "rule__CustomLineDecoration__Group__0");
					put(grammarAccess.getColorAccess().getGroup(), "rule__Color__Group__0");
					put(grammarAccess.getDefaultLayoutAccess().getGroup_0(), "rule__DefaultLayout__Group_0__0");
					put(grammarAccess.getDefaultLayoutAccess().getGroup_1(), "rule__DefaultLayout__Group_1__0");
					put(grammarAccess.getCustomLayoutAccess().getGroup(), "rule__CustomLayout__Group__0");
					put(grammarAccess.getRoundedAccess().getGroup(), "rule__Rounded__Group__0");
					put(grammarAccess.getRegularPolygonAccess().getGroup(), "rule__RegularPolygon__Group__0");
					put(grammarAccess.getEllipseAccess().getGroup(), "rule__Ellipse__Group__0");
					put(grammarAccess.getCustomFigureAccess().getGroup(), "rule__CustomFigure__Group__0");
					put(grammarAccess.getPointAccess().getGroup(), "rule__Point__Group__0");
					put(grammarAccess.getSizeAccess().getGroup(), "rule__Size__Group__0");
					put(grammarAccess.getGraphicalDefinitionAccess().getGroup(), "rule__GraphicalDefinition__Group__0");
					put(grammarAccess.getNodeElementDefAccess().getGroup(), "rule__NodeElementDef__Group__0");
					put(grammarAccess.getNodeElementAltAccess().getGroup(), "rule__NodeElementAlt__Group__0");
					put(grammarAccess.getNodeElementAltAccess().getGroup_5(), "rule__NodeElementAlt__Group_5__0");
					put(grammarAccess.getNodeElementAltAccess().getGroup_7(), "rule__NodeElementAlt__Group_7__0");
					put(grammarAccess.getRegularFigureAccess().getGroup(), "rule__RegularFigure__Group__0");
					put(grammarAccess.getRegularFigureAccess().getGroup_8(), "rule__RegularFigure__Group_8__0");
					put(grammarAccess.getImageFigureAccess().getGroup(), "rule__ImageFigure__Group__0");
					put(grammarAccess.getComplexFigureAccess().getGroup(), "rule__ComplexFigure__Group__0");
					put(grammarAccess.getNodeLinkDefAccess().getGroup(), "rule__NodeLinkDef__Group__0");
					put(grammarAccess.getNodeLinkAltAccess().getGroup(), "rule__NodeLinkAlt__Group__0");
					put(grammarAccess.getNodeLinkAltAccess().getGroup_5(), "rule__NodeLinkAlt__Group_5__0");
					put(grammarAccess.getNodeLinkAltAccess().getGroup_6(), "rule__NodeLinkAlt__Group_6__0");
					put(grammarAccess.getNodeLinkAltAccess().getGroup_7(), "rule__NodeLinkAlt__Group_7__0");
					put(grammarAccess.getNodeLineDefAccess().getGroup(), "rule__NodeLineDef__Group__0");
					put(grammarAccess.getNodeLineAltAccess().getGroup(), "rule__NodeLineAlt__Group__0");
					put(grammarAccess.getNodeLineAltAccess().getGroup_5(), "rule__NodeLineAlt__Group_5__0");
					put(grammarAccess.getNodeLineAltAccess().getGroup_6(), "rule__NodeLineAlt__Group_6__0");
					put(grammarAccess.getNodeLineAltAccess().getGroup_7(), "rule__NodeLineAlt__Group_7__0");
					put(grammarAccess.getInterNodeDefAccess().getGroup(), "rule__InterNodeDef__Group__0");
					put(grammarAccess.getInterNodeAltAccess().getGroup(), "rule__InterNodeAlt__Group__0");
					put(grammarAccess.getExternalNodeDefAccess().getGroup(), "rule__ExternalNodeDef__Group__0");
					put(grammarAccess.getExternalNodeAltAccess().getGroup(), "rule__ExternalNodeAlt__Group__0");
					put(grammarAccess.getRulesDefinitionAccess().getGroup(), "rule__RulesDefinition__Group__0");
					put(grammarAccess.getRuleForTypeAccess().getGroup(), "rule__RuleForType__Group__0");
					put(grammarAccess.getRuleForReferenceAccess().getGroup(), "rule__RuleForReference__Group__0");
					put(grammarAccess.getCaseTypeAccess().getGroup(), "rule__CaseType__Group__0");
					put(grammarAccess.getCaseReferenceAccess().getGroup(), "rule__CaseReference__Group__0");
					put(grammarAccess.getInteractionDefinitionAccess().getGroup(), "rule__InteractionDefinition__Group__0");
					put(grammarAccess.getElementWizardAccess().getGroup(), "rule__ElementWizard__Group__0");
					put(grammarAccess.getPageAccess().getGroup(), "rule__Page__Group__0");
					put(grammarAccess.getPageAccess().getGroup_7(), "rule__Page__Group_7__0");
					put(grammarAccess.getPageAccess().getGroup_8(), "rule__Page__Group_8__0");
					put(grammarAccess.getPageAccess().getGroup_9(), "rule__Page__Group_9__0");
					put(grammarAccess.getAttMapAccess().getGroup(), "rule__AttMap__Group__0");
					put(grammarAccess.getButtonAccess().getGroup(), "rule__Button__Group__0");
					put(grammarAccess.getPersonalWizardAccess().getGroup(), "rule__PersonalWizard__Group__0");
					put(grammarAccess.getPredefinedViewAccess().getGroup(), "rule__PredefinedView__Group__0");
					put(grammarAccess.getPredefinedViewAccess().getGroup_11(), "rule__PredefinedView__Group_11__0");
					put(grammarAccess.getShowChildsAccess().getGroup(), "rule__ShowChilds__Group__0");
					put(grammarAccess.getShowSelectionAccess().getGroup(), "rule__ShowSelection__Group__0");
					put(grammarAccess.getShowSelectionAccess().getGroup_3(), "rule__ShowSelection__Group_3__0");
					put(grammarAccess.getCountTypesAccess().getGroup(), "rule__CountTypes__Group__0");
					put(grammarAccess.getViewStyleAccess().getGroup_2(), "rule__ViewStyle__Group_2__0");
					put(grammarAccess.getPersonalViewAccess().getGroup(), "rule__PersonalView__Group__0");
					put(grammarAccess.getStatementAccess().getGroup(), "rule__Statement__Group__0");
					put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
					put(grammarAccess.getMouseEventAccess().getGroup_0(), "rule__MouseEvent__Group_0__0");
					put(grammarAccess.getMouseEventAccess().getGroup_1(), "rule__MouseEvent__Group_1__0");
					put(grammarAccess.getMouseEventAccess().getGroup_2(), "rule__MouseEvent__Group_2__0");
					put(grammarAccess.getMouseEventAccess().getGroup_3(), "rule__MouseEvent__Group_3__0");
					put(grammarAccess.getMouseEventAccess().getGroup_4(), "rule__MouseEvent__Group_4__0");
					put(grammarAccess.getMouseEventAccess().getGroup_5(), "rule__MouseEvent__Group_5__0");
					put(grammarAccess.getMouseEventAccess().getGroup_6(), "rule__MouseEvent__Group_6__0");
					put(grammarAccess.getMouseEventAccess().getGroup_7(), "rule__MouseEvent__Group_7__0");
					put(grammarAccess.getMouseEventAccess().getGroup_8(), "rule__MouseEvent__Group_8__0");
					put(grammarAccess.getKeyEventAccess().getGroup_0(), "rule__KeyEvent__Group_0__0");
					put(grammarAccess.getKeyEventAccess().getGroup_1(), "rule__KeyEvent__Group_1__0");
					put(grammarAccess.getKeyEventAccess().getGroup_2(), "rule__KeyEvent__Group_2__0");
					put(grammarAccess.getMenuEventAccess().getGroup(), "rule__MenuEvent__Group__0");
					put(grammarAccess.getWizardStartAccess().getGroup(), "rule__WizardStart__Group__0");
					put(grammarAccess.getViewDeployAccess().getGroup(), "rule__ViewDeploy__Group__0");
					put(grammarAccess.getClassExecutionAccess().getGroup(), "rule__ClassExecution__Group__0");
					put(grammarAccess.getModelAccess().getImportsAssignment_1(), "rule__Model__ImportsAssignment_1");
					put(grammarAccess.getModelAccess().getGraphicalREpresentationAssignment_2(), "rule__Model__GraphicalREpresentationAssignment_2");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getImportAccess().getNameAssignment_3(), "rule__Import__NameAssignment_3");
					put(grammarAccess.getGraphicalRepresentationAccess().getNameAssignment_2(), "rule__GraphicalRepresentation__NameAssignment_2");
					put(grammarAccess.getGraphicalRepresentationAccess().getReferencePackageAssignment_4_2(), "rule__GraphicalRepresentation__ReferencePackageAssignment_4_2");
					put(grammarAccess.getGraphicalRepresentationAccess().getRootAssignment_5(), "rule__GraphicalRepresentation__RootAssignment_5");
					put(grammarAccess.getGraphicalRepresentationAccess().getToolsDefinitionAssignment_6(), "rule__GraphicalRepresentation__ToolsDefinitionAssignment_6");
					put(grammarAccess.getGraphicalRepresentationAccess().getStyleDefinitionAssignment_7(), "rule__GraphicalRepresentation__StyleDefinitionAssignment_7");
					put(grammarAccess.getGraphicalRepresentationAccess().getGraphicalDefinitionAssignment_8(), "rule__GraphicalRepresentation__GraphicalDefinitionAssignment_8");
					put(grammarAccess.getGraphicalRepresentationAccess().getRulesDefinitionAssignment_9(), "rule__GraphicalRepresentation__RulesDefinitionAssignment_9");
					put(grammarAccess.getGraphicalRepresentationAccess().getInteractionDefinitionAssignment_10(), "rule__GraphicalRepresentation__InteractionDefinitionAssignment_10");
					put(grammarAccess.getClassReferenceAccess().getClassAssignment_1(), "rule__ClassReference__ClassAssignment_1");
					put(grammarAccess.getAttReferenceAccess().getClassAssignment_1(), "rule__AttReference__ClassAssignment_1");
					put(grammarAccess.getROOTAccess().getNameAssignment_1(), "rule__ROOT__NameAssignment_1");
					put(grammarAccess.getToolDefinitionAccess().getNameAssignment_2(), "rule__ToolDefinition__NameAssignment_2");
					put(grammarAccess.getToolDefinitionAccess().getToolGroupsAssignment_4(), "rule__ToolDefinition__ToolGroupsAssignment_4");
					put(grammarAccess.getToolGroupAccess().getNameAssignment_1(), "rule__ToolGroup__NameAssignment_1");
					put(grammarAccess.getToolGroupAccess().getDescriptionAssignment_4(), "rule__ToolGroup__DescriptionAssignment_4");
					put(grammarAccess.getToolGroupAccess().getToolGroupsAssignment_5(), "rule__ToolGroup__ToolGroupsAssignment_5");
					put(grammarAccess.getToolGroupAccess().getButtonsAssignment_6(), "rule__ToolGroup__ButtonsAssignment_6");
					put(grammarAccess.getCreationButtonAccess().getMetaConceptReferenceAssignment_2(), "rule__CreationButton__MetaConceptReferenceAssignment_2");
					put(grammarAccess.getCreationButtonAccess().getNameAssignment_5(), "rule__CreationButton__NameAssignment_5");
					put(grammarAccess.getCreationButtonAccess().getDescriptionAssignment_7(), "rule__CreationButton__DescriptionAssignment_7");
					put(grammarAccess.getCreationButtonAccess().getIconAssignment_9(), "rule__CreationButton__IconAssignment_9");
					put(grammarAccess.getStyleDefinitionAccess().getStyleElementsAssignment_3(), "rule__StyleDefinition__StyleElementsAssignment_3");
					put(grammarAccess.getLineStyleAccess().getNameAssignment_1(), "rule__LineStyle__NameAssignment_1");
					put(grammarAccess.getLineStyleAccess().getWidthAssignment_4(), "rule__LineStyle__WidthAssignment_4");
					put(grammarAccess.getLineStyleAccess().getLineTypeAssignment_6(), "rule__LineStyle__LineTypeAssignment_6");
					put(grammarAccess.getLineStyleAccess().getColorAssignment_8(), "rule__LineStyle__ColorAssignment_8");
					put(grammarAccess.getDefaultLineDecorationAccess().getNoneAssignment_0(), "rule__DefaultLineDecoration__NoneAssignment_0");
					put(grammarAccess.getDefaultLineDecorationAccess().getArrowAssignment_1(), "rule__DefaultLineDecoration__ArrowAssignment_1");
					put(grammarAccess.getDefaultLineDecorationAccess().getRhombAssignment_2(), "rule__DefaultLineDecoration__RhombAssignment_2");
					put(grammarAccess.getDefaultLineDecorationAccess().getFilledrhombAssignment_3_0(), "rule__DefaultLineDecoration__FilledrhombAssignment_3_0");
					put(grammarAccess.getDefaultLineDecorationAccess().getSquareAssignment_4(), "rule__DefaultLineDecoration__SquareAssignment_4");
					put(grammarAccess.getDefaultLineDecorationAccess().getFilledsquareAssignment_5_0(), "rule__DefaultLineDecoration__FilledsquareAssignment_5_0");
					put(grammarAccess.getDefaultLineDecorationAccess().getClosedarrowAssignment_6_0(), "rule__DefaultLineDecoration__ClosedarrowAssignment_6_0");
					put(grammarAccess.getDefaultLineDecorationAccess().getFilledclosedarrowAssignment_7_0(), "rule__DefaultLineDecoration__FilledclosedarrowAssignment_7_0");
					put(grammarAccess.getCustomLineDecorationAccess().getNameAssignment_1(), "rule__CustomLineDecoration__NameAssignment_1");
					put(grammarAccess.getCustomLineDecorationAccess().getReferenceImplementationAssignment_4(), "rule__CustomLineDecoration__ReferenceImplementationAssignment_4");
					put(grammarAccess.getColorAccess().getNameAssignment_1(), "rule__Color__NameAssignment_1");
					put(grammarAccess.getColorAccess().getRedAssignment_3(), "rule__Color__RedAssignment_3");
					put(grammarAccess.getColorAccess().getGreenAssignment_5(), "rule__Color__GreenAssignment_5");
					put(grammarAccess.getColorAccess().getBlueAssignment_7(), "rule__Color__BlueAssignment_7");
					put(grammarAccess.getDefaultLayoutAccess().getListAssignment_0_0(), "rule__DefaultLayout__ListAssignment_0_0");
					put(grammarAccess.getDefaultLayoutAccess().getDefaultAssignment_1_0(), "rule__DefaultLayout__DefaultAssignment_1_0");
					put(grammarAccess.getCustomLayoutAccess().getReferenceImplementationAssignment_4(), "rule__CustomLayout__ReferenceImplementationAssignment_4");
					put(grammarAccess.getRoundedAccess().getNameAssignment_1(), "rule__Rounded__NameAssignment_1");
					put(grammarAccess.getRoundedAccess().getRxAssignment_4(), "rule__Rounded__RxAssignment_4");
					put(grammarAccess.getRoundedAccess().getRyAssignment_6(), "rule__Rounded__RyAssignment_6");
					put(grammarAccess.getRegularPolygonAccess().getNameAssignment_1(), "rule__RegularPolygon__NameAssignment_1");
					put(grammarAccess.getRegularPolygonAccess().getVertexCantAssignment_4(), "rule__RegularPolygon__VertexCantAssignment_4");
					put(grammarAccess.getRegularPolygonAccess().getStartAngleAssignment_6(), "rule__RegularPolygon__StartAngleAssignment_6");
					put(grammarAccess.getEllipseAccess().getNameAssignment_1(), "rule__Ellipse__NameAssignment_1");
					put(grammarAccess.getEllipseAccess().getRadioxAssignment_5(), "rule__Ellipse__RadioxAssignment_5");
					put(grammarAccess.getEllipseAccess().getRadioyAssignment_7(), "rule__Ellipse__RadioyAssignment_7");
					put(grammarAccess.getCustomFigureAccess().getNameAssignment_1(), "rule__CustomFigure__NameAssignment_1");
					put(grammarAccess.getCustomFigureAccess().getPointsAssignment_3(), "rule__CustomFigure__PointsAssignment_3");
					put(grammarAccess.getPointAccess().getXAssignment_3(), "rule__Point__XAssignment_3");
					put(grammarAccess.getPointAccess().getYAssignment_5(), "rule__Point__YAssignment_5");
					put(grammarAccess.getLabelPositionAccess().getInternalAssignment_0(), "rule__LabelPosition__InternalAssignment_0");
					put(grammarAccess.getLabelPositionAccess().getExternalAssignment_1(), "rule__LabelPosition__ExternalAssignment_1");
					put(grammarAccess.getSizeAccess().getWidthAssignment_2(), "rule__Size__WidthAssignment_2");
					put(grammarAccess.getSizeAccess().getHeightAssignment_4(), "rule__Size__HeightAssignment_4");
					put(grammarAccess.getGraphicalDefinitionAccess().getElementsAssignment_4(), "rule__GraphicalDefinition__ElementsAssignment_4");
					put(grammarAccess.getNodeElementDefAccess().getNameAssignment_1(), "rule__NodeElementDef__NameAssignment_1");
					put(grammarAccess.getNodeElementDefAccess().getReferenceClassAssignment_3(), "rule__NodeElementDef__ReferenceClassAssignment_3");
					put(grammarAccess.getNodeElementDefAccess().getLabelAssignment_6(), "rule__NodeElementDef__LabelAssignment_6");
					put(grammarAccess.getNodeElementDefAccess().getLabelIconAssignment_9(), "rule__NodeElementDef__LabelIconAssignment_9");
					put(grammarAccess.getNodeElementDefAccess().getLabelPlacementAssignment_12(), "rule__NodeElementDef__LabelPlacementAssignment_12");
					put(grammarAccess.getNodeElementDefAccess().getSizeAssignment_14(), "rule__NodeElementDef__SizeAssignment_14");
					put(grammarAccess.getNodeElementDefAccess().getFigureAssignment_15(), "rule__NodeElementDef__FigureAssignment_15");
					put(grammarAccess.getNodeElementDefAccess().getPhantomNAssignment_17(), "rule__NodeElementDef__PhantomNAssignment_17");
					put(grammarAccess.getNodeElementAltAccess().getNameAssignment_1(), "rule__NodeElementAlt__NameAssignment_1");
					put(grammarAccess.getNodeElementAltAccess().getParentAssignment_3(), "rule__NodeElementAlt__ParentAssignment_3");
					put(grammarAccess.getNodeElementAltAccess().getLabelPlacementAssignment_5_2(), "rule__NodeElementAlt__LabelPlacementAssignment_5_2");
					put(grammarAccess.getNodeElementAltAccess().getFigureAssignment_6(), "rule__NodeElementAlt__FigureAssignment_6");
					put(grammarAccess.getNodeElementAltAccess().getSizeAssignment_7_1(), "rule__NodeElementAlt__SizeAssignment_7_1");
					put(grammarAccess.getRegularFigureAccess().getFigureStyleAssignment_2(), "rule__RegularFigure__FigureStyleAssignment_2");
					put(grammarAccess.getRegularFigureAccess().getBacgroundColorAssignment_5(), "rule__RegularFigure__BacgroundColorAssignment_5");
					put(grammarAccess.getRegularFigureAccess().getBorderAssignment_7(), "rule__RegularFigure__BorderAssignment_7");
					put(grammarAccess.getRegularFigureAccess().getPathAssignment_8_2(), "rule__RegularFigure__PathAssignment_8_2");
					put(grammarAccess.getRegularFigureAccess().getSizeAssignment_8_5(), "rule__RegularFigure__SizeAssignment_8_5");
					put(grammarAccess.getRegularFigureAccess().getPositionAssignment_8_8(), "rule__RegularFigure__PositionAssignment_8_8");
					put(grammarAccess.getImageFigureAccess().getPathAssignment_4(), "rule__ImageFigure__PathAssignment_4");
					put(grammarAccess.getComplexFigureAccess().getImplementationReferenceAssignment_4(), "rule__ComplexFigure__ImplementationReferenceAssignment_4");
					put(grammarAccess.getNodeLinkDefAccess().getNameAssignment_1(), "rule__NodeLinkDef__NameAssignment_1");
					put(grammarAccess.getNodeLinkDefAccess().getReferenceClassAssignment_3(), "rule__NodeLinkDef__ReferenceClassAssignment_3");
					put(grammarAccess.getNodeLinkDefAccess().getLabelAssignment_6(), "rule__NodeLinkDef__LabelAssignment_6");
					put(grammarAccess.getNodeLinkDefAccess().getStyleAssignment_8(), "rule__NodeLinkDef__StyleAssignment_8");
					put(grammarAccess.getNodeLinkDefAccess().getSourceDecorationAssignment_11(), "rule__NodeLinkDef__SourceDecorationAssignment_11");
					put(grammarAccess.getNodeLinkDefAccess().getTargetDecorationAssignment_14(), "rule__NodeLinkDef__TargetDecorationAssignment_14");
					put(grammarAccess.getNodeLinkDefAccess().getSourceReferenceAssignment_18(), "rule__NodeLinkDef__SourceReferenceAssignment_18");
					put(grammarAccess.getNodeLinkDefAccess().getTargetReferenceAssignment_22(), "rule__NodeLinkDef__TargetReferenceAssignment_22");
					put(grammarAccess.getNodeLinkAltAccess().getNameAssignment_1(), "rule__NodeLinkAlt__NameAssignment_1");
					put(grammarAccess.getNodeLinkAltAccess().getParentAssignment_3(), "rule__NodeLinkAlt__ParentAssignment_3");
					put(grammarAccess.getNodeLinkAltAccess().getStyleAssignment_5_1(), "rule__NodeLinkAlt__StyleAssignment_5_1");
					put(grammarAccess.getNodeLinkAltAccess().getSourceDecorationAssignment_6_2(), "rule__NodeLinkAlt__SourceDecorationAssignment_6_2");
					put(grammarAccess.getNodeLinkAltAccess().getTargetDecorationAssignment_7_2(), "rule__NodeLinkAlt__TargetDecorationAssignment_7_2");
					put(grammarAccess.getNodeLineDefAccess().getNameAssignment_1(), "rule__NodeLineDef__NameAssignment_1");
					put(grammarAccess.getNodeLineDefAccess().getReferenceNameAssignment_3(), "rule__NodeLineDef__ReferenceNameAssignment_3");
					put(grammarAccess.getNodeLineDefAccess().getLabelAssignment_6(), "rule__NodeLineDef__LabelAssignment_6");
					put(grammarAccess.getNodeLineDefAccess().getStyleAssignment_8(), "rule__NodeLineDef__StyleAssignment_8");
					put(grammarAccess.getNodeLineDefAccess().getSourceDecorationAssignment_11(), "rule__NodeLineDef__SourceDecorationAssignment_11");
					put(grammarAccess.getNodeLineDefAccess().getTargetDecorationAssignment_14(), "rule__NodeLineDef__TargetDecorationAssignment_14");
					put(grammarAccess.getNodeLineAltAccess().getNameAssignment_1(), "rule__NodeLineAlt__NameAssignment_1");
					put(grammarAccess.getNodeLineAltAccess().getParentAssignment_3(), "rule__NodeLineAlt__ParentAssignment_3");
					put(grammarAccess.getNodeLineAltAccess().getStyleAssignment_5_1(), "rule__NodeLineAlt__StyleAssignment_5_1");
					put(grammarAccess.getNodeLineAltAccess().getSourceDecorationAssignment_6_2(), "rule__NodeLineAlt__SourceDecorationAssignment_6_2");
					put(grammarAccess.getNodeLineAltAccess().getTargetDecorationAssignment_7_2(), "rule__NodeLineAlt__TargetDecorationAssignment_7_2");
					put(grammarAccess.getInterNodeDefAccess().getNameAssignment_1(), "rule__InterNodeDef__NameAssignment_1");
					put(grammarAccess.getInterNodeDefAccess().getReferenceNameAssignment_3(), "rule__InterNodeDef__ReferenceNameAssignment_3");
					put(grammarAccess.getInterNodeDefAccess().getLayoutAssignment_6(), "rule__InterNodeDef__LayoutAssignment_6");
					put(grammarAccess.getInterNodeAltAccess().getNameAssignment_1(), "rule__InterNodeAlt__NameAssignment_1");
					put(grammarAccess.getInterNodeAltAccess().getParentAssignment_3(), "rule__InterNodeAlt__ParentAssignment_3");
					put(grammarAccess.getInterNodeAltAccess().getLayoutAssignment_6(), "rule__InterNodeAlt__LayoutAssignment_6");
					put(grammarAccess.getExternalNodeDefAccess().getNameAssignment_1(), "rule__ExternalNodeDef__NameAssignment_1");
					put(grammarAccess.getExternalNodeDefAccess().getReferenceNameAssignment_3(), "rule__ExternalNodeDef__ReferenceNameAssignment_3");
					put(grammarAccess.getExternalNodeDefAccess().getSizeAssignment_6(), "rule__ExternalNodeDef__SizeAssignment_6");
					put(grammarAccess.getExternalNodeAltAccess().getNameAssignment_1(), "rule__ExternalNodeAlt__NameAssignment_1");
					put(grammarAccess.getExternalNodeAltAccess().getParentAssignment_3(), "rule__ExternalNodeAlt__ParentAssignment_3");
					put(grammarAccess.getExternalNodeAltAccess().getSizeAssignment_6(), "rule__ExternalNodeAlt__SizeAssignment_6");
					put(grammarAccess.getRulesDefinitionAccess().getRulessAssignment_3(), "rule__RulesDefinition__RulessAssignment_3");
					put(grammarAccess.getRuleForTypeAccess().getClassReferenceAssignment_1(), "rule__RuleForType__ClassReferenceAssignment_1");
					put(grammarAccess.getRuleForTypeAccess().getCasesAssignment_3(), "rule__RuleForType__CasesAssignment_3");
					put(grammarAccess.getRuleForReferenceAccess().getReferenceAssignment_1(), "rule__RuleForReference__ReferenceAssignment_1");
					put(grammarAccess.getRuleForReferenceAccess().getCasesAssignment_3(), "rule__RuleForReference__CasesAssignment_3");
					put(grammarAccess.getCaseTypeAccess().getConditionAssignment_2(), "rule__CaseType__ConditionAssignment_2");
					put(grammarAccess.getCaseTypeAccess().getNodeElementAssignment_4_0(), "rule__CaseType__NodeElementAssignment_4_0");
					put(grammarAccess.getCaseReferenceAccess().getConditionAssignment_2(), "rule__CaseReference__ConditionAssignment_2");
					put(grammarAccess.getCaseReferenceAccess().getReferenceElementAssignment_4_0(), "rule__CaseReference__ReferenceElementAssignment_4_0");
					put(grammarAccess.getInteractionDefinitionAccess().getInteractionElementsAssignment_5(), "rule__InteractionDefinition__InteractionElementsAssignment_5");
					put(grammarAccess.getInteractionDefinitionAccess().getStatementsAssignment_9(), "rule__InteractionDefinition__StatementsAssignment_9");
					put(grammarAccess.getElementWizardAccess().getNameAssignment_1(), "rule__ElementWizard__NameAssignment_1");
					put(grammarAccess.getElementWizardAccess().getClassReferenceAssignment_4(), "rule__ElementWizard__ClassReferenceAssignment_4");
					put(grammarAccess.getElementWizardAccess().getTitleAssignment_7(), "rule__ElementWizard__TitleAssignment_7");
					put(grammarAccess.getElementWizardAccess().getDescriptionAssignment_9(), "rule__ElementWizard__DescriptionAssignment_9");
					put(grammarAccess.getElementWizardAccess().getTypeAssignment_11(), "rule__ElementWizard__TypeAssignment_11");
					put(grammarAccess.getElementWizardAccess().getPagesAssignment_14(), "rule__ElementWizard__PagesAssignment_14");
					put(grammarAccess.getElementWizardAccess().getDefaultButtonsAssignment_18(), "rule__ElementWizard__DefaultButtonsAssignment_18");
					put(grammarAccess.getPageAccess().getTitleAssignment_4(), "rule__Page__TitleAssignment_4");
					put(grammarAccess.getPageAccess().getDescriptionAssignment_6(), "rule__Page__DescriptionAssignment_6");
					put(grammarAccess.getPageAccess().getAttributesAssignment_7_2(), "rule__Page__AttributesAssignment_7_2");
					put(grammarAccess.getPageAccess().getReferencesAssignment_8_2(), "rule__Page__ReferencesAssignment_8_2");
					put(grammarAccess.getPageAccess().getButtonsAssignment_9_2(), "rule__Page__ButtonsAssignment_9_2");
					put(grammarAccess.getAttMapAccess().getAttributeAssignment_2(), "rule__AttMap__AttributeAssignment_2");
					put(grammarAccess.getAttMapAccess().getLabelAssignment_4(), "rule__AttMap__LabelAssignment_4");
					put(grammarAccess.getAttMapAccess().getComponentAssignment_6(), "rule__AttMap__ComponentAssignment_6");
					put(grammarAccess.getAttMapAccess().getDefaultValueAssignment_8(), "rule__AttMap__DefaultValueAssignment_8");
					put(grammarAccess.getButtonAccess().getLabelAssignment_3(), "rule__Button__LabelAssignment_3");
					put(grammarAccess.getButtonAccess().getMethodActionAssignment_5(), "rule__Button__MethodActionAssignment_5");
					put(grammarAccess.getPersonalWizardAccess().getNameAssignment_2(), "rule__PersonalWizard__NameAssignment_2");
					put(grammarAccess.getPersonalWizardAccess().getReferenceImplementationAssignment_5(), "rule__PersonalWizard__ReferenceImplementationAssignment_5");
					put(grammarAccess.getPredefinedViewAccess().getNameAssignment_1(), "rule__PredefinedView__NameAssignment_1");
					put(grammarAccess.getPredefinedViewAccess().getTitleAssignment_4(), "rule__PredefinedView__TitleAssignment_4");
					put(grammarAccess.getPredefinedViewAccess().getDescriptionAssignment_6(), "rule__PredefinedView__DescriptionAssignment_6");
					put(grammarAccess.getPredefinedViewAccess().getTypeAssignment_8(), "rule__PredefinedView__TypeAssignment_8");
					put(grammarAccess.getPredefinedViewAccess().getStyleAssignment_10(), "rule__PredefinedView__StyleAssignment_10");
					put(grammarAccess.getPredefinedViewAccess().getReferenceImplementationAssignment_11_3(), "rule__PredefinedView__ReferenceImplementationAssignment_11_3");
					put(grammarAccess.getShowChildsAccess().getClassReferenceAssignment_5(), "rule__ShowChilds__ClassReferenceAssignment_5");
					put(grammarAccess.getShowSelectionAccess().getClassReferenceAssignment_3_2(), "rule__ShowSelection__ClassReferenceAssignment_3_2");
					put(grammarAccess.getCountTypesAccess().getClassReferenceAssignment_5(), "rule__CountTypes__ClassReferenceAssignment_5");
					put(grammarAccess.getViewStyleAccess().getTreeAssignment_0(), "rule__ViewStyle__TreeAssignment_0");
					put(grammarAccess.getViewStyleAccess().getSelectionAssignment_1(), "rule__ViewStyle__SelectionAssignment_1");
					put(grammarAccess.getViewStyleAccess().getTableAssignment_2_0(), "rule__ViewStyle__TableAssignment_2_0");
					put(grammarAccess.getViewStyleAccess().getResultGraphicAssignment_2_1(), "rule__ViewStyle__ResultGraphicAssignment_2_1");
					put(grammarAccess.getPersonalViewAccess().getNameAssignment_1(), "rule__PersonalView__NameAssignment_1");
					put(grammarAccess.getPersonalViewAccess().getReferenceImplementationAssignment_4(), "rule__PersonalView__ReferenceImplementationAssignment_4");
					put(grammarAccess.getStatementAccess().getClassReferenceAssignment_1(), "rule__Statement__ClassReferenceAssignment_1");
					put(grammarAccess.getStatementAccess().getEventsAssignment_3(), "rule__Statement__EventsAssignment_3");
					put(grammarAccess.getEventAccess().getEventTypeAssignment_2(), "rule__Event__EventTypeAssignment_2");
					put(grammarAccess.getEventAccess().getInstructionsAssignment_5(), "rule__Event__InstructionsAssignment_5");
					put(grammarAccess.getMouseEventAccess().getMouseDownAssignment_0_0(), "rule__MouseEvent__MouseDownAssignment_0_0");
					put(grammarAccess.getMouseEventAccess().getMouseEnterAssignment_1_0(), "rule__MouseEvent__MouseEnterAssignment_1_0");
					put(grammarAccess.getMouseEventAccess().getMouseHorizontalWheelAssignment_2_0(), "rule__MouseEvent__MouseHorizontalWheelAssignment_2_0");
					put(grammarAccess.getMouseEventAccess().getMouseUpAssignment_3_0(), "rule__MouseEvent__MouseUpAssignment_3_0");
					put(grammarAccess.getMouseEventAccess().getMouseWheelAssignment_4_0(), "rule__MouseEvent__MouseWheelAssignment_4_0");
					put(grammarAccess.getMouseEventAccess().getMouseVerticalWheelAssignment_5_0(), "rule__MouseEvent__MouseVerticalWheelAssignment_5_0");
					put(grammarAccess.getMouseEventAccess().getMouseHoverAssignment_6_0(), "rule__MouseEvent__MouseHoverAssignment_6_0");
					put(grammarAccess.getMouseEventAccess().getMouseExitAssignment_7_0(), "rule__MouseEvent__MouseExitAssignment_7_0");
					put(grammarAccess.getMouseEventAccess().getMouseDoubleClickAssignment_8_0(), "rule__MouseEvent__MouseDoubleClickAssignment_8_0");
					put(grammarAccess.getKeyEventAccess().getKeyPressAssignment_0_0(), "rule__KeyEvent__KeyPressAssignment_0_0");
					put(grammarAccess.getKeyEventAccess().getKeyUpAssignment_1_0(), "rule__KeyEvent__KeyUpAssignment_1_0");
					put(grammarAccess.getKeyEventAccess().getKeyDownAssignment_2_0(), "rule__KeyEvent__KeyDownAssignment_2_0");
					put(grammarAccess.getElementEventAccess().getCreateAssignment_0(), "rule__ElementEvent__CreateAssignment_0");
					put(grammarAccess.getElementEventAccess().getDeleteAssignment_1(), "rule__ElementEvent__DeleteAssignment_1");
					put(grammarAccess.getMenuEventAccess().getNameAssignment_3(), "rule__MenuEvent__NameAssignment_3");
					put(grammarAccess.getWizardStartAccess().getWizardAssignment_2(), "rule__WizardStart__WizardAssignment_2");
					put(grammarAccess.getViewDeployAccess().getViewAssignment_2(), "rule__ViewDeploy__ViewAssignment_2");
					put(grammarAccess.getClassExecutionAccess().getInplementationReferenceAssignment_1(), "rule__ClassExecution__InplementationReferenceAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			co.edu.uniandes.enar.ui.contentassist.antlr.internal.InternalPictureParser typedParser = (co.edu.uniandes.enar.ui.contentassist.antlr.internal.InternalPictureParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public PictureGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PictureGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
