/*
* generated by Xtext
*/
package co.edu.uniandes.enar;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PictureUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return co.edu.uniandes.enar.ui.internal.PictureActivator.getInstance().getInjector("co.edu.uniandes.enar.Picture");
	}
	
}
