/*
 * generated by Xtext
 */
package co.edu.uniandes.enar.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PictureUiModule extends co.edu.uniandes.enar.ui.AbstractPictureUiModule {
	public PictureUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
