/*
 * generated by Xtext
 */
package co.edu.uniandes.enar;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PictureRuntimeModule extends co.edu.uniandes.enar.AbstractPictureRuntimeModule {

}
