/*
* generated by Xtext
*/
package co.edu.uniandes.enar;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PictureStandaloneSetup extends PictureStandaloneSetupGenerated{

	public static void doSetup() {
		new PictureStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

