<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="technologyLayer"
    nsURI="http://uniandes.edu.co/metamodels/technologyLayer" nsPrefix="technologyLayer">
  <eClassifiers xsi:type="ecore:EClass" name="ArchimateModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ArchimateElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchimateElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfArtifactArtifact"
        upperBound="-1" eType="#//Artifact" containment="true" eOpposite="#//Artifact/composesArtifactArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesArtifactArtifact"
        eType="#//Artifact" eOpposite="#//Artifact/composedOfArtifactArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesArtifactArtifact"
        upperBound="-1" eType="#//Artifact" eOpposite="#//Artifact/aggregatedByArtifactArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByArtifactArtifact"
        eType="#//Artifact" eOpposite="#//Artifact/aggregatesArtifactArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessedByInfrastructureServiceArtifact"
        upperBound="-1" eType="#//InfrastructureService" eOpposite="#//InfrastructureService/accessesArtifactInfrastructureService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToNodeArtifact"
        upperBound="-1" eType="#//Node" eOpposite="#//Node/assignedToArtifactNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfrastructureService" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfInfrastructureServiceInfrastructureService"
        upperBound="-1" eType="#//InfrastructureService" containment="true" eOpposite="#//InfrastructureService/composesInfrastructureServiceInfrastructureService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesInfrastructureServiceInfrastructureService"
        eType="#//InfrastructureService" eOpposite="#//InfrastructureService/composedOfInfrastructureServiceInfrastructureService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesInfrastructureServiceInfrastructureService"
        upperBound="-1" eType="#//InfrastructureService" eOpposite="#//InfrastructureService/aggregatedByInfrastructureServiceInfrastructureService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByInfrastructureServiceInfrastructureService"
        eType="#//InfrastructureService" eOpposite="#//InfrastructureService/aggregatesInfrastructureServiceInfrastructureService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessesArtifactInfrastructureService"
        upperBound="-1" eType="#//Artifact" eOpposite="#//Artifact/accessedByInfrastructureServiceArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToInfrastructureInterfaceInfrastructureService"
        upperBound="-1" eType="#//InfrastructureInterface" eOpposite="#//InfrastructureInterface/assignedToInfrastructureServiceInfrastructureInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedByNodeInfrastructureService"
        upperBound="-1" eType="#//Node" eOpposite="#//Node/usesInfrastructureServiceNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfrastructureInterface" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfInfrastructureInterfaceInfrastructureInterface"
        upperBound="-1" eType="#//InfrastructureInterface" containment="true" eOpposite="#//InfrastructureInterface/composesInfrastructureInterfaceInfrastructureInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesInfrastructureInterfaceInfrastructureInterface"
        eType="#//InfrastructureInterface" eOpposite="#//InfrastructureInterface/composedOfInfrastructureInterfaceInfrastructureInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesInfrastructureInterfaceInfrastructureInterface"
        upperBound="-1" eType="#//InfrastructureInterface" eOpposite="#//InfrastructureInterface/aggregatedByInfrastructureInterfaceInfrastructureInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByInfrastructureInterfaceInfrastructureInterface"
        eType="#//InfrastructureInterface" eOpposite="#//InfrastructureInterface/aggregatesInfrastructureInterfaceInfrastructureInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesNodeInfrastructureInterface"
        eType="#//Node" eOpposite="#//Node/composedOfInfrastructureInterfaceNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToInfrastructureServiceInfrastructureInterface"
        upperBound="-1" eType="#//InfrastructureService" eOpposite="#//InfrastructureService/assignedToInfrastructureInterfaceInfrastructureService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedByNodeInfrastructureInterface"
        upperBound="-1" eType="#//Node" eOpposite="#//Node/usesInfrastructureInterfaceNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfNodeNode" upperBound="-1"
        eType="#//Node" containment="true" eOpposite="#//Node/composesNodeNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesNodeNode" eType="#//Node"
        eOpposite="#//Node/composedOfNodeNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesNodeNode" upperBound="-1"
        eType="#//Node" eOpposite="#//Node/aggregatedByNodeNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByNodeNode" eType="#//Node"
        eOpposite="#//Node/aggregatesNodeNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedWithCommunicationPathNode"
        eType="#//CommunicationPath" eOpposite="#//CommunicationPath/associatedWithNodeCommunicationPath"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToArtifactNode"
        upperBound="-1" eType="#//Artifact" eOpposite="#//Artifact/assignedToNodeArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfInfrastructureInterfaceNode"
        upperBound="-1" eType="#//InfrastructureInterface" containment="true" eOpposite="#//InfrastructureInterface/composesNodeInfrastructureInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usesInfrastructureInterfaceNode"
        upperBound="-1" eType="#//InfrastructureInterface" eOpposite="#//InfrastructureInterface/usedByNodeInfrastructureInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usesInfrastructureServiceNode"
        upperBound="-1" eType="#//InfrastructureService" eOpposite="#//InfrastructureService/realizedByNodeInfrastructureService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemSoftware" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfSystemSoftwareSystemSoftware"
        upperBound="-1" eType="#//SystemSoftware" containment="true" eOpposite="#//SystemSoftware/composesSystemSoftwareSystemSoftware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesSystemSoftwareSystemSoftware"
        eType="#//SystemSoftware" eOpposite="#//SystemSoftware/composedOfSystemSoftwareSystemSoftware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesSystemSoftwareSystemSoftware"
        upperBound="-1" eType="#//SystemSoftware" eOpposite="#//SystemSoftware/aggregatedBySystemSoftwareSystemSoftware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedBySystemSoftwareSystemSoftware"
        eType="#//SystemSoftware" eOpposite="#//SystemSoftware/aggregatesSystemSoftwareSystemSoftware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToDeviceSystemSoftware"
        upperBound="-1" eType="#//Device" eOpposite="#//Device/assignedToSystemSoftwareDevice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfDeviceDevice"
        upperBound="-1" eType="#//Device" containment="true" eOpposite="#//Device/composesDeviceDevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesDeviceDevice" eType="#//Device"
        eOpposite="#//Device/composedOfDeviceDevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesDeviceDevice"
        upperBound="-1" eType="#//Device" eOpposite="#//Device/aggregatedByDeviceDevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByDeviceDevice"
        eType="#//Device" eOpposite="#//Device/aggregatesDeviceDevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedWithNetworkDevice"
        eType="#//Network" eOpposite="#//Network/associatedWithDeviceNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToSystemSoftwareDevice"
        upperBound="-1" eType="#//SystemSoftware" eOpposite="#//SystemSoftware/assignedToDeviceSystemSoftware"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationPath" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfCommunicationPathCommunicationPath"
        upperBound="-1" eType="#//CommunicationPath" containment="true" eOpposite="#//CommunicationPath/composesCommunicationPathCommunicationPath"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesCommunicationPathCommunicationPath"
        eType="#//CommunicationPath" eOpposite="#//CommunicationPath/composedOfCommunicationPathCommunicationPath"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesCommunicationPathCommunicationPath"
        upperBound="-1" eType="#//CommunicationPath" eOpposite="#//CommunicationPath/aggregatedByCommunicationPathCommunicationPath"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByCommunicationPathCommunicationPath"
        eType="#//CommunicationPath" eOpposite="#//CommunicationPath/aggregatesCommunicationPathCommunicationPath"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedWithNodeCommunicationPath"
        eType="#//Node" eOpposite="#//Node/associatedWithCommunicationPathNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedByNetworkCommunicationPath"
        upperBound="-1" eType="#//Network" eOpposite="#//Network/realizesCommunicationPathNetwork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfNetworkNetwork"
        upperBound="-1" eType="#//Network" containment="true" eOpposite="#//Network/composesNetworkNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesNetworkNetwork"
        eType="#//Network" eOpposite="#//Network/composedOfNetworkNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesNetworkNetwork"
        upperBound="-1" eType="#//Network" eOpposite="#//Network/aggregatedByNetworkNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByNetworkNetwork"
        eType="#//Network" eOpposite="#//Network/aggregatesNetworkNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizesCommunicationPathNetwork"
        eType="#//CommunicationPath" eOpposite="#//CommunicationPath/realizedByNetworkCommunicationPath"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedWithDeviceNetwork"
        eType="#//Device" eOpposite="#//Device/associatedWithNetworkDevice"/>
  </eClassifiers>
</ecore:EPackage>
