/*
 * generated by Xtext
 */
package co.edu.uniandes.enar.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import co.edu.uniandes.enar.ui.internal.PictureActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PictureExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PictureActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PictureActivator.getInstance().getInjector(PictureActivator.CO_EDU_UNIANDES_ENAR_PICTURE);
	}
	
}
