<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="businessLayer" nsURI="http://uniandes.edu.co/metamodels/businessLayer"
    nsPrefix="businessLayer">
  <eClassifiers xsi:type="ecore:EClass" name="ArchimateModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ArchimateElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchimateElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Organization" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfOrganizationOrganization"
        upperBound="-1" eType="#//Organization" eOpposite="#//Organization/composesOrganizationOrganization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesOrganizationOrganization"
        eType="#//Organization" eOpposite="#//Organization/composedOfOrganizationOrganization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesOrganizationOrganization"
        upperBound="-1" eType="#//Organization" eOpposite="#//Organization/aggregatedByOrganizationOrganization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByOrganizationOrganization"
        eType="#//Organization" eOpposite="#//Organization/aggregatesOrganizationOrganization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/organization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processes" upperBound="-1"
        eType="#//BusinessProcess" eOpposite="#//BusinessProcess/organization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//BusinessRole" eOpposite="#//BusinessRole/organization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//BusinessActor" eOpposite="#//BusinessActor/organization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessServices" upperBound="-1"
        eType="#//BusinessService" eOpposite="#//BusinessService/organization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignedTask" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfAssignedTaskAssignedTask"
        upperBound="-1" eType="#//AssignedTask" eOpposite="#//AssignedTask/composesAssignedTaskAssignedTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesAssignedTaskAssignedTask"
        eType="#//AssignedTask" eOpposite="#//AssignedTask/composedOfAssignedTaskAssignedTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesAssignedTaskAssignedTask"
        upperBound="-1" eType="#//AssignedTask" eOpposite="#//AssignedTask/aggregatedByAssignedTaskAssignedTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByAssignedTaskAssignedTask"
        eType="#//AssignedTask" eOpposite="#//AssignedTask/aggregatesAssignedTaskAssignedTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assigned" eType="#//BusinessActor"
        eOpposite="#//BusinessActor/assignedTasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentTask" eType="#//Task"
        eOpposite="#//Task/taskInstances"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfTaskTask" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/composesTaskTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesTaskTask" eType="#//Task"
        eOpposite="#//Task/composedOfTaskTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesTaskTask" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/aggregatedByTaskTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByTaskTask" eType="#//Task"
        eOpposite="#//Task/aggregatesTaskTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resposinbles" upperBound="-1"
        eType="#//BusinessRole" eOpposite="#//BusinessRole/tasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskInstances" upperBound="-1"
        eType="#//AssignedTask" eOpposite="#//AssignedTask/parentTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organization" eType="#//Organization"
        eOpposite="#//Organization/tasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supports" eType="#//ManualActivity"
        eOpposite="#//ManualActivity/realizableBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfActivityActivity"
        upperBound="-1" eType="#//Activity" eOpposite="#//Activity/composesActivityActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesActivityActivity"
        eType="#//Activity" eOpposite="#//Activity/composedOfActivityActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesActivityActivity"
        upperBound="-1" eType="#//Activity" eOpposite="#//Activity/aggregatedByActivityActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByActivityActivity"
        eType="#//Activity" eOpposite="#//Activity/aggregatesActivityActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessProcessprocess"
        eType="#//BusinessProcess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManualActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfManualActivityManualActivity"
        upperBound="-1" eType="#//ManualActivity" eOpposite="#//ManualActivity/composesManualActivityManualActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesManualActivityManualActivity"
        eType="#//ManualActivity" eOpposite="#//ManualActivity/composedOfManualActivityManualActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesManualActivityManualActivity"
        upperBound="-1" eType="#//ManualActivity" eOpposite="#//ManualActivity/aggregatedByManualActivityManualActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByManualActivityManualActivity"
        eType="#//ManualActivity" eOpposite="#//ManualActivity/aggregatesManualActivityManualActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizableBy" eType="#//Task"
        eOpposite="#//Task/supports"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutomaticActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfAutomaticActivityAutomaticActivity"
        upperBound="-1" eType="#//AutomaticActivity" eOpposite="#//AutomaticActivity/composesAutomaticActivityAutomaticActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesAutomaticActivityAutomaticActivity"
        eType="#//AutomaticActivity" eOpposite="#//AutomaticActivity/composedOfAutomaticActivityAutomaticActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesAutomaticActivityAutomaticActivity"
        upperBound="-1" eType="#//AutomaticActivity" eOpposite="#//AutomaticActivity/aggregatedByAutomaticActivityAutomaticActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByAutomaticActivityAutomaticActivity"
        eType="#//AutomaticActivity" eOpposite="#//AutomaticActivity/aggregatesAutomaticActivityAutomaticActivity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfValueValue" upperBound="-1"
        eType="#//Value" eOpposite="#//Value/composesValueValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesValueValue" eType="#//Value"
        eOpposite="#//Value/composedOfValueValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesValueValue" upperBound="-1"
        eType="#//Value" eOpposite="#//Value/aggregatedByValueValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByValueValue"
        eType="#//Value" eOpposite="#//Value/aggregatesValueValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedWithProductValue"
        eType="#//Product" eOpposite="#//Product/associatedWithValueProduct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfProductProduct"
        upperBound="-1" eType="#//Product" eOpposite="#//Product/composesProductProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesProductProduct"
        eType="#//Product" eOpposite="#//Product/composedOfProductProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesProductProduct"
        upperBound="-1" eType="#//Product" eOpposite="#//Product/aggregatedByProductProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByProductProduct"
        eType="#//Product" eOpposite="#//Product/aggregatesProductProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedWithValueProduct"
        eType="#//Value" eOpposite="#//Value/associatedWithProductValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesContractProduct"
        upperBound="-1" eType="#//Contract" eOpposite="#//Contract/aggregatedByProductContract"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesBusinessServiceProduct"
        upperBound="-1" eType="#//BusinessService" eOpposite="#//BusinessService/aggregatedByProductBusinessService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Meaning" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfMeaningMeaning"
        upperBound="-1" eType="#//Meaning" eOpposite="#//Meaning/composesMeaningMeaning"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesMeaningMeaning"
        eType="#//Meaning" eOpposite="#//Meaning/composedOfMeaningMeaning"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesMeaningMeaning"
        upperBound="-1" eType="#//Meaning" eOpposite="#//Meaning/aggregatedByMeaningMeaning"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByMeaningMeaning"
        eType="#//Meaning" eOpposite="#//Meaning/aggregatesMeaningMeaning"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedWithBusinessObjectMeaning"
        eType="#//BusinessObject" eOpposite="#//BusinessObject/associatedWithMeaningBusinessObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Representation" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfRepresentationRepresentation"
        upperBound="-1" eType="#//Representation" eOpposite="#//Representation/composesRepresentationRepresentation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesRepresentationRepresentation"
        eType="#//Representation" eOpposite="#//Representation/composedOfRepresentationRepresentation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesRepresentationRepresentation"
        upperBound="-1" eType="#//Representation" eOpposite="#//Representation/aggregatedByRepresentationRepresentation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByRepresentationRepresentation"
        eType="#//Representation" eOpposite="#//Representation/aggregatesRepresentationRepresentation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizesBusinessObjectRepresentation"
        eType="#//BusinessObject" eOpposite="#//BusinessObject/realizedByRepresentationBusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedFromLocationRepresentation"
        upperBound="-1" eType="#//Location" eOpposite="#//Location/assignedToRepresentationLocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessObject" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfBusinessObjectBusinessObject"
        upperBound="-1" eType="#//BusinessObject" eOpposite="#//BusinessObject/composesBusinessObjectBusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesBusinessObjectBusinessObject"
        eType="#//BusinessObject" eOpposite="#//BusinessObject/composedOfBusinessObjectBusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesBusinessObjectBusinessObject"
        upperBound="-1" eType="#//BusinessObject" eOpposite="#//BusinessObject/aggregatedByBusinessObjectBusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByBusinessObjectBusinessObject"
        eType="#//BusinessObject" eOpposite="#//BusinessObject/aggregatesBusinessObjectBusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedWithMeaningBusinessObject"
        eType="#//Meaning" eOpposite="#//Meaning/associatedWithBusinessObjectMeaning"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedByRepresentationBusinessObject"
        upperBound="-1" eType="#//Representation" eOpposite="#//Representation/realizesBusinessObjectRepresentation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessedByBusinessBehaviorElementBusinessObject"
        upperBound="-1" eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/accessesBusinessObjectBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessedByBusinessServiceBusinessObject"
        upperBound="-1" eType="#//BusinessService" eOpposite="#//BusinessService/accessesBusinessObjectBusinessService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessedByBusinessEventBusinessObject"
        upperBound="-1" eType="#//BusinessEvent" eOpposite="#//BusinessEvent/accessesBusinessObjectBusinessEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedFromLocationBusinessObject"
        upperBound="-1" eType="#//Location" eOpposite="#//Location/assignedToBusinessObjectLocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contract" eSuperTypes="#//BusinessObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfContractContract"
        upperBound="-1" eType="#//Contract" eOpposite="#//Contract/composesContractContract"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesContractContract"
        eType="#//Contract" eOpposite="#//Contract/composedOfContractContract"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesContractContract"
        upperBound="-1" eType="#//Contract" eOpposite="#//Contract/aggregatedByContractContract"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByContractContract"
        eType="#//Contract" eOpposite="#//Contract/aggregatesContractContract"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByProductContract"
        eType="#//Product" eOpposite="#//Product/aggregatesContractProduct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessService" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfBusinessServiceBusinessService"
        upperBound="-1" eType="#//BusinessService" eOpposite="#//BusinessService/composesBusinessServiceBusinessService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesBusinessServiceBusinessService"
        eType="#//BusinessService" eOpposite="#//BusinessService/composedOfBusinessServiceBusinessService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesBusinessServiceBusinessService"
        upperBound="-1" eType="#//BusinessService" eOpposite="#//BusinessService/aggregatedByBusinessServiceBusinessService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByBusinessServiceBusinessService"
        eType="#//BusinessService" eOpposite="#//BusinessService/aggregatesBusinessServiceBusinessService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByProductBusinessService"
        eType="#//Product" eOpposite="#//Product/aggregatesBusinessServiceProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedByBusinessActorBusinessService"
        upperBound="-1" eType="#//BusinessActor" eOpposite="#//BusinessActor/usesBusinessServiceBusinessActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedByBusinessBehaviorElementBusinessService"
        upperBound="-1" eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/realisesBusinessServiceBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedByBusinessBehaviorElementBusinessService"
        upperBound="-1" eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/usesBusinessServiceBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedFromBusinessInterfaceBusinessService"
        upperBound="-1" eType="#//BusinessInterface" eOpposite="#//BusinessInterface/assignedToBusinessServiceBusinessInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessesBusinessObjectBusinessService"
        upperBound="-1" eType="#//BusinessObject" eOpposite="#//BusinessObject/accessedByBusinessServiceBusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedByBusinessRoleBusinessService"
        upperBound="-1" eType="#//BusinessRole" eOpposite="#//BusinessRole/usesBusinessServiceBusinessRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organization" upperBound="-1"
        eType="#//Organization" eOpposite="#//Organization/businessServices"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessBehaviorElement" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfBusinessBehaviorElementBusinessBehaviorElement"
        upperBound="-1" eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/composesBusinessBehaviorElementBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesBusinessBehaviorElementBusinessBehaviorElement"
        eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/composedOfBusinessBehaviorElementBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesBusinessBehaviorElementBusinessBehaviorElement"
        upperBound="-1" eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/aggregatedByBusinessBehaviorElementBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByBusinessBehaviorElementBusinessBehaviorElement"
        eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/aggregatesBusinessBehaviorElementBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggersToBusinessBehaviorElementBusinessBehaviorElement"
        upperBound="-1" eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/triggeredByBusinessBehaviorElementBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggeredByBusinessBehaviorElementBusinessBehaviorElement"
        upperBound="-1" eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/triggersToBusinessBehaviorElementBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowsFromBusinessBehaviorElementBusinessBehaviorElement"
        upperBound="-1" eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/flowsToBusinessBehaviorElementBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowsToBusinessBehaviorElementBusinessBehaviorElement"
        upperBound="-1" eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/flowsFromBusinessBehaviorElementBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realisesBusinessServiceBusinessBehaviorElement"
        eType="#//BusinessService" eOpposite="#//BusinessService/realizedByBusinessBehaviorElementBusinessService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usesBusinessServiceBusinessBehaviorElement"
        upperBound="-1" eType="#//BusinessService" eOpposite="#//BusinessService/usedByBusinessBehaviorElementBusinessService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggersBusinessEventBusinessBehaviorElement"
        upperBound="-1" eType="#//BusinessEvent" eOpposite="#//BusinessEvent/triggeredByBusinessBehaviorElementBusinessEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggeredByBusinessEventBusinessBehaviorElement"
        upperBound="-1" eType="#//BusinessEvent" eOpposite="#//BusinessEvent/triggersBusinessBehaviorElementBusinessEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessesBusinessObjectBusinessBehaviorElement"
        upperBound="-1" eType="#//BusinessObject" eOpposite="#//BusinessObject/accessedByBusinessBehaviorElementBusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedFromBusinessRoleBusinessBehaviorElement"
        upperBound="-1" eType="#//BusinessRole" eOpposite="#//BusinessRole/assignedToBusinessBehaviorElementBusinessRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessProcess" eSuperTypes="#//BusinessBehaviorElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processFullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processDesign" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="missionary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organization" upperBound="-1"
        eType="#//Organization" eOpposite="#//Organization/processes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessFunction" eSuperTypes="#//BusinessBehaviorElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessInteraction" eSuperTypes="#//BusinessBehaviorElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessEvent" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfBusinessEventBusinessEvent"
        upperBound="-1" eType="#//BusinessEvent" eOpposite="#//BusinessEvent/composesBusinessEventBusinessEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesBusinessEventBusinessEvent"
        eType="#//BusinessEvent" eOpposite="#//BusinessEvent/composedOfBusinessEventBusinessEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesBusinessEventBusinessEvent"
        upperBound="-1" eType="#//BusinessEvent" eOpposite="#//BusinessEvent/aggregatedByBusinessEventBusinessEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByBusinessEventBusinessEvent"
        eType="#//BusinessEvent" eOpposite="#//BusinessEvent/aggregatesBusinessEventBusinessEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggeredByBusinessBehaviorElementBusinessEvent"
        upperBound="-1" eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/triggersBusinessEventBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggersBusinessBehaviorElementBusinessEvent"
        upperBound="-1" eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/triggeredByBusinessEventBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessesBusinessObjectBusinessEvent"
        upperBound="-1" eType="#//BusinessObject" eOpposite="#//BusinessObject/accessedByBusinessEventBusinessObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfLocationLocation"
        upperBound="-1" eType="#//Location" eOpposite="#//Location/composesLocationLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesLocationLocation"
        eType="#//Location" eOpposite="#//Location/composedOfLocationLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesLocationLocation"
        upperBound="-1" eType="#//Location" eOpposite="#//Location/aggregatedByLocationLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByLocationLocation"
        eType="#//Location" eOpposite="#//Location/aggregatesLocationLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToBusinessActorLocation"
        upperBound="-1" eType="#//BusinessActor" eOpposite="#//BusinessActor/assignedFromLocationBusinessActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToBusinessObjectLocation"
        upperBound="-1" eType="#//BusinessObject" eOpposite="#//BusinessObject/assignedFromLocationBusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToRepresentationLocation"
        upperBound="-1" eType="#//Representation" eOpposite="#//Representation/assignedFromLocationRepresentation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessInterface" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfBusinessInterfaceBusinessInterface"
        upperBound="-1" eType="#//BusinessInterface" eOpposite="#//BusinessInterface/composesBusinessInterfaceBusinessInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesBusinessInterfaceBusinessInterface"
        eType="#//BusinessInterface" eOpposite="#//BusinessInterface/composedOfBusinessInterfaceBusinessInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesBusinessInterfaceBusinessInterface"
        upperBound="-1" eType="#//BusinessInterface" eOpposite="#//BusinessInterface/aggregatedByBusinessInterfaceBusinessInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByBusinessInterfaceBusinessInterface"
        eType="#//BusinessInterface" eOpposite="#//BusinessInterface/aggregatesBusinessInterfaceBusinessInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesBusinessRoleBusinessInterface"
        eType="#//BusinessRole" eOpposite="#//BusinessRole/composedOfBusinessInterfaceBusinessRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedByBusinessActorBusinessInterface"
        upperBound="-1" eType="#//BusinessActor" eOpposite="#//BusinessActor/usesBusinessInterfaceBusinessActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedByBusinessRoleBusinessInterface"
        upperBound="-1" eType="#//BusinessRole" eOpposite="#//BusinessRole/usesBusinessInterfaceBusinessRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToBusinessServiceBusinessInterface"
        upperBound="-1" eType="#//BusinessService" eOpposite="#//BusinessService/assignedFromBusinessInterfaceBusinessService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessRole" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rank" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfBusinessRoleBusinessRole"
        upperBound="-1" eType="#//BusinessRole" eOpposite="#//BusinessRole/composesBusinessRoleBusinessRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesBusinessRoleBusinessRole"
        eType="#//BusinessRole" eOpposite="#//BusinessRole/composedOfBusinessRoleBusinessRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesBusinessRoleBusinessRole"
        upperBound="-1" eType="#//BusinessRole" eOpposite="#//BusinessRole/aggregatedByBusinessRoleBusinessRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByBusinessRoleBusinessRole"
        eType="#//BusinessRole" eOpposite="#//BusinessRole/aggregatesBusinessRoleBusinessRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToBusinessBehaviorElementBusinessRole"
        upperBound="-1" eType="#//BusinessBehaviorElement" eOpposite="#//BusinessBehaviorElement/assignedFromBusinessRoleBusinessBehaviorElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByBusinessCollaborationBusinessRole"
        eType="#//BusinessCollaboration" eOpposite="#//BusinessCollaboration/aggregatesBusinessRoleBusinessCollaboration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedFromBusinessActorBusinessRole"
        upperBound="-1" eType="#//BusinessActor" eOpposite="#//BusinessActor/assignedToBusinessRoleBusinessActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfBusinessInterfaceBusinessRole"
        upperBound="-1" eType="#//BusinessInterface" containment="true" eOpposite="#//BusinessInterface/composesBusinessRoleBusinessInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usesBusinessInterfaceBusinessRole"
        upperBound="-1" eType="#//BusinessInterface" eOpposite="#//BusinessInterface/usedByBusinessRoleBusinessInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usesBusinessServiceBusinessRole"
        upperBound="-1" eType="#//BusinessService" eOpposite="#//BusinessService/usedByBusinessRoleBusinessService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organization" upperBound="-1"
        eType="#//Organization" eOpposite="#//Organization/roles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/resposinbles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessCollaboration" eSuperTypes="#//BusinessRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesBusinessActorBusinessCollaboration"
        upperBound="-1" eType="#//BusinessActor" eOpposite="#//BusinessActor/aggregatedByBusinessCollaborationBusinessActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesBusinessRoleBusinessCollaboration"
        upperBound="-1" eType="#//BusinessRole" eOpposite="#//BusinessRole/aggregatedByBusinessCollaborationBusinessRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessActor" eSuperTypes="#//ArchimateElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedOfBusinessActorBusinessActor"
        upperBound="-1" eType="#//BusinessActor" eOpposite="#//BusinessActor/composesBusinessActorBusinessActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composesBusinessActorBusinessActor"
        eType="#//BusinessActor" eOpposite="#//BusinessActor/composedOfBusinessActorBusinessActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatesBusinessActorBusinessActor"
        upperBound="-1" eType="#//BusinessActor" eOpposite="#//BusinessActor/aggregatedByBusinessActorBusinessActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByBusinessActorBusinessActor"
        eType="#//BusinessActor" eOpposite="#//BusinessActor/aggregatesBusinessActorBusinessActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedByBusinessCollaborationBusinessActor"
        upperBound="-1" eType="#//BusinessCollaboration" eOpposite="#//BusinessCollaboration/aggregatesBusinessActorBusinessCollaboration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usesBusinessInterfaceBusinessActor"
        upperBound="-1" eType="#//BusinessInterface" eOpposite="#//BusinessInterface/usedByBusinessActorBusinessInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usesBusinessServiceBusinessActor"
        upperBound="-1" eType="#//BusinessService" eOpposite="#//BusinessService/usedByBusinessActorBusinessService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedToBusinessRoleBusinessActor"
        upperBound="-1" eType="#//BusinessRole" eOpposite="#//BusinessRole/assignedFromBusinessActorBusinessRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedFromLocationBusinessActor"
        upperBound="-1" eType="#//Location" eOpposite="#//Location/assignedToBusinessActorLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organization" upperBound="-1"
        eType="#//Organization" eOpposite="#//Organization/persons"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedTasks" upperBound="-1"
        eType="#//AssignedTask" eOpposite="#//AssignedTask/assigned"/>
  </eClassifiers>
</ecore:EPackage>
